### PR TITLE
In-progress upgrade

### PR DESCRIPTION
**Pull request by ohbadiah**
Hi there. As a first foray into rust, I'm trying to upgrade this library's dependencies to the latest version of hyper and to use serde instead of rustc-serialize (#2). I'm a ways away yet, but I thought I would open this in order to let you know. Feel free to offer any advice or assistance.

### CODE REVIEW

**Comment by nathankot** [comment]
👋 @ohbadiah cool to see this! I haven't touched Rust in a long time now, but happy to take a look when it's ready.

Just a heads up, we actually have version 2 of the Plaid API so if you're intent on using Plaid through Rust it might be worth upgrading this repo which was built against version 1 to 2, or starting a new repo for v2: https://plaid.com/docs/

**Comment by ohbadiah** [comment]
@nathankot Hmm, thanks for the heads up about the versioning. Depending on how significant the jump is it might make sense to start over, informed by the existing client.

So I understand, though, the API docs mention that the initial release of the API was 2017-03-08. That's the initial release of version 2, then?

**Comment by nathankot** [comment]
@ohbadiah 

> Depending on how significant the jump is it might make sense to start over, informed by the existing client.

IMO the significance is big enough, and this repo has been untouched for long enough to justify starting over 🙈

>  the API docs mention that the initial release of the API was 2017-03-08. That's the initial release of version 2, then?

That is correct! We don't mention the old version of the API anymore as we're phasing it out :)

**Comment by ohbadiah** [comment]
Do you have a previous upgrade guide outlining the differences? That will make the existing code a little more useful guide for starting a new client.

**Comment by nathankot** [comment]
@ohbadiah we do have this, hope that it's helpful!
https://plaid.com/docs/link/transition-guide/#creating-new-items

**Pull request closed without merging**
